// <auto-generated />
using System;
using KafkaLoad.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KafkaLoad.Infrastructure.Migrations
{
    [DbContext(typeof(KafkaLoadDbContext))]
    [Migration("20260408213134_RemoveBootstrapAndTopicFromConfig")]
    partial class RemoveBootstrapAndTopicFromConfig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("KafkaLoad.Infrastructure.Database.Entities.ConsumerConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AutoOffsetReset")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("auto_offset_reset");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("FetchMaxBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fetch_max_bytes");

                    b.Property<int>("FetchMaxWaitMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fetch_max_wait_ms");

                    b.Property<int>("FetchMinBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("fetch_min_bytes");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("group_id");

                    b.Property<int>("MaxPollIntervalMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_poll_interval_ms");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("SaslMechanism")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sasl_mechanism");

                    b.Property<string>("SaslPassword")
                        .HasColumnType("TEXT")
                        .HasColumnName("sasl_password");

                    b.Property<string>("SaslUsername")
                        .HasColumnType("TEXT")
                        .HasColumnName("sasl_username");

                    b.Property<string>("SecurityProtocol")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("security_protocol");

                    b.Property<string>("SslCaLocation")
                        .HasColumnType("TEXT")
                        .HasColumnName("ssl_ca_location");

                    b.Property<string>("SslCertificateLocation")
                        .HasColumnType("TEXT")
                        .HasColumnName("ssl_certificate_location");

                    b.Property<string>("SslKeyLocation")
                        .HasColumnType("TEXT")
                        .HasColumnName("ssl_key_location");

                    b.Property<string>("SslKeyPassword")
                        .HasColumnType("TEXT")
                        .HasColumnName("ssl_key_password");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("consumer_config", (string)null);
                });

            modelBuilder.Entity("KafkaLoad.Infrastructure.Database.Entities.ConsumerMetricsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double>("AvgE2ELatencyMs")
                        .HasColumnType("REAL")
                        .HasColumnName("avg_e2e_latency_ms");

                    b.Property<long>("ErrorCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("error_count");

                    b.Property<long>("FinalConsumerLag")
                        .HasColumnType("INTEGER")
                        .HasColumnName("final_consumer_lag");

                    b.Property<long>("MaxConsumerLag")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_consumer_lag");

                    b.Property<double>("MaxE2ELatencyMs")
                        .HasColumnType("REAL")
                        .HasColumnName("max_e2e_latency_ms");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("report_id");

                    b.Property<long>("SuccessConsumed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("success_consumed");

                    b.Property<double>("ThroughputBytesSec")
                        .HasColumnType("REAL")
                        .HasColumnName("throughput_bytes_sec");

                    b.Property<double>("ThroughputMsgSec")
                        .HasColumnType("REAL")
                        .HasColumnName("throughput_msg_sec");

                    b.Property<long>("TotalBytesConsumed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_bytes_consumed");

                    b.Property<long>("TotalConsumed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_consumed");

                    b.HasKey("Id");

                    b.HasIndex("ReportId")
                        .IsUnique();

                    b.ToTable("consumer_metrics", (string)null);
                });

            modelBuilder.Entity("KafkaLoad.Infrastructure.Database.Entities.ProducerConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Acks")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("acks");

                    b.Property<bool>("AutoCreateTopicsEnable")
                        .HasColumnType("INTEGER")
                        .HasColumnName("auto_create_topics_enable");

                    b.Property<int>("BatchSizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("batch_size_bytes");

                    b.Property<long>("BufferMemoryBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("buffer_memory_bytes");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("client_id");

                    b.Property<string>("CompressionType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("compression_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<bool>("EnableIdempotence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enable_idempotence");

                    b.Property<double>("LingerMs")
                        .HasColumnType("REAL")
                        .HasColumnName("linger_ms");

                    b.Property<int>("MaxInFlightRequests")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_in_flight_requests");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Retries")
                        .HasColumnType("INTEGER")
                        .HasColumnName("retries");

                    b.Property<string>("SaslMechanism")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("sasl_mechanism");

                    b.Property<string>("SaslPassword")
                        .HasColumnType("TEXT")
                        .HasColumnName("sasl_password");

                    b.Property<string>("SaslUsername")
                        .HasColumnType("TEXT")
                        .HasColumnName("sasl_username");

                    b.Property<string>("SecurityProtocol")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("security_protocol");

                    b.Property<string>("SslCaLocation")
                        .HasColumnType("TEXT")
                        .HasColumnName("ssl_ca_location");

                    b.Property<string>("SslCertificateLocation")
                        .HasColumnType("TEXT")
                        .HasColumnName("ssl_certificate_location");

                    b.Property<string>("SslKeyLocation")
                        .HasColumnType("TEXT")
                        .HasColumnName("ssl_key_location");

                    b.Property<string>("SslKeyPassword")
                        .HasColumnType("TEXT")
                        .HasColumnName("ssl_key_password");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("producer_config", (string)null);
                });

            modelBuilder.Entity("KafkaLoad.Infrastructure.Database.Entities.ProducerMetricsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double>("AvgLatencyMs")
                        .HasColumnType("REAL")
                        .HasColumnName("avg_latency_ms");

                    b.Property<long>("ErrorCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("error_count");

                    b.Property<double>("ErrorRatePercent")
                        .HasColumnType("REAL")
                        .HasColumnName("error_rate_percent");

                    b.Property<double>("MaxLatencyMs")
                        .HasColumnType("REAL")
                        .HasColumnName("max_latency_ms");

                    b.Property<double>("P95LatencyMs")
                        .HasColumnType("REAL")
                        .HasColumnName("p95_latency_ms");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("report_id");

                    b.Property<long>("SuccessSent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("success_sent");

                    b.Property<double>("ThroughputBytesSec")
                        .HasColumnType("REAL")
                        .HasColumnName("throughput_bytes_sec");

                    b.Property<double>("ThroughputMsgSec")
                        .HasColumnType("REAL")
                        .HasColumnName("throughput_msg_sec");

                    b.Property<long>("TotalAttempted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_attempted");

                    b.Property<long>("TotalBytesSent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_bytes_sent");

                    b.HasKey("Id");

                    b.HasIndex("ReportId")
                        .IsUnique();

                    b.ToTable("producer_metrics", (string)null);
                });

            modelBuilder.Entity("KafkaLoad.Infrastructure.Database.Entities.TestReportEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("ConsumersCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("consumers_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_seconds");

                    b.Property<int>("MessageSizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("message_size_bytes");

                    b.Property<int>("ProducersCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("producers_count");

                    b.Property<int?>("ScenarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("scenario_id");

                    b.Property<string>("ScenarioName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("scenario_name");

                    b.Property<double?>("TargetThroughput")
                        .HasColumnType("REAL")
                        .HasColumnName("target_throughput");

                    b.Property<string>("TestType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("test_type");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("topic_name");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("test_report", (string)null);
                });

            modelBuilder.Entity("KafkaLoad.Infrastructure.Database.Entities.TestScenarioEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("BaseThroughput")
                        .HasColumnType("INTEGER")
                        .HasColumnName("base_throughput");

                    b.Property<int?>("ConsumerConfigId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("consumer_config_id");

                    b.Property<int?>("ConsumerCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("consumer_count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("duration_seconds");

                    b.Property<string>("FixedTemplate")
                        .HasColumnType("TEXT")
                        .HasColumnName("fixed_template");

                    b.Property<string>("KeyStrategy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key_strategy");

                    b.Property<int?>("MessageSizeBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("message_size_bytes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int?>("ProducerConfigId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("producer_config_id");

                    b.Property<int?>("ProducerCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("producer_count");

                    b.Property<int?>("SpikeThroughput")
                        .HasColumnType("INTEGER")
                        .HasColumnName("spike_throughput");

                    b.Property<int?>("TargetThroughput")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_throughput");

                    b.Property<string>("TestType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("test_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("ValueStrategy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value_strategy");

                    b.HasKey("Id");

                    b.HasIndex("ConsumerConfigId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ProducerConfigId");

                    b.ToTable("test_scenario", (string)null);
                });

            modelBuilder.Entity("KafkaLoad.Infrastructure.Database.Entities.TimeSeriesPointEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ReportId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("report_id");

                    b.Property<string>("SeriesName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("series_name");

                    b.Property<double>("TimeSeconds")
                        .HasColumnType("REAL")
                        .HasColumnName("time_seconds");

                    b.Property<double>("Value")
                        .HasColumnType("REAL")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("time_series_point", (string)null);
                });

            modelBuilder.Entity("KafkaLoad.Infrastructure.Database.Entities.ConsumerMetricsEntity", b =>
                {
                    b.HasOne("KafkaLoad.Infrastructure.Database.Entities.TestReportEntity", "Report")
                        .WithOne("ConsumerMetrics")
                        .HasForeignKey("KafkaLoad.Infrastructure.Database.Entities.ConsumerMetricsEntity", "ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("KafkaLoad.Infrastructure.Database.Entities.ProducerMetricsEntity", b =>
                {
                    b.HasOne("KafkaLoad.Infrastructure.Database.Entities.TestReportEntity", "Report")
                        .WithOne("ProducerMetrics")
                        .HasForeignKey("KafkaLoad.Infrastructure.Database.Entities.ProducerMetricsEntity", "ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("KafkaLoad.Infrastructure.Database.Entities.TestReportEntity", b =>
                {
                    b.HasOne("KafkaLoad.Infrastructure.Database.Entities.TestScenarioEntity", "Scenario")
                        .WithMany("Reports")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("KafkaLoad.Infrastructure.Database.Entities.TestScenarioEntity", b =>
                {
                    b.HasOne("KafkaLoad.Infrastructure.Database.Entities.ConsumerConfigEntity", "ConsumerConfig")
                        .WithMany("ScenariosAsConsumer")
                        .HasForeignKey("ConsumerConfigId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KafkaLoad.Infrastructure.Database.Entities.ProducerConfigEntity", "ProducerConfig")
                        .WithMany("ScenariosAsProducer")
                        .HasForeignKey("ProducerConfigId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ConsumerConfig");

                    b.Navigation("ProducerConfig");
                });

            modelBuilder.Entity("KafkaLoad.Infrastructure.Database.Entities.TimeSeriesPointEntity", b =>
                {
                    b.HasOne("KafkaLoad.Infrastructure.Database.Entities.TestReportEntity", "Report")
                        .WithMany("TimeSeriesPoints")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("KafkaLoad.Infrastructure.Database.Entities.ConsumerConfigEntity", b =>
                {
                    b.Navigation("ScenariosAsConsumer");
                });

            modelBuilder.Entity("KafkaLoad.Infrastructure.Database.Entities.ProducerConfigEntity", b =>
                {
                    b.Navigation("ScenariosAsProducer");
                });

            modelBuilder.Entity("KafkaLoad.Infrastructure.Database.Entities.TestReportEntity", b =>
                {
                    b.Navigation("ConsumerMetrics");

                    b.Navigation("ProducerMetrics");

                    b.Navigation("TimeSeriesPoints");
                });

            modelBuilder.Entity("KafkaLoad.Infrastructure.Database.Entities.TestScenarioEntity", b =>
                {
                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
